version: "2"

volumes:
    pgdb:

services:
    redis:
        image: redis:3.0-alpine

    postgres:
        image: postgres:9.6-alpine
        environment:
            POSTGRES_PASSWORD: dev
            POSTGRES_USER: sentry
        volumes:
            - pgdb:/var/lib/postgresql/data

    sentry:
        image: sentry:8.15.0
        depends_on:
            - redis
            - postgres
        ports:
            - "8080:9000"
        environment:
            SENTRY_SECRET_KEY: mysentry_secret_key
            SENTRY_POSTGRES_HOST: postgres
            SENTRY_DB_USER: sentry
            SENTRY_DB_PASSWORD: dev
            SENTRY_REDIS_HOST: redis
            #SENTRY_SERVER_EMAIL:
            #SENTRY_EMAIL_HOST:
            #SENTRY_EMAIL_PORT:

    sentry-cron:
        image: sentry:8.15.0
        depends_on:
            - redis
            - postgres
        command: "sentry run cron"
        environment:
            SENTRY_SECRET_KEY: mysentry_secret_key
            SENTRY_POSTGRES_HOST: postgres
            SENTRY_DB_USER: sentry
            SENTRY_DB_PASSWORD: dev
            SENTRY_REDIS_HOST: redis

    sentry-worker:
        image: sentry:8.15.0
        depends_on:
            - redis
            - postgres
        command: "sentry run worker"
        environment:
            SENTRY_SECRET_KEY: mysentry_secret_key
            SENTRY_POSTGRES_HOST: postgres
            SENTRY_DB_USER: sentry
            SENTRY_DB_PASSWORD: dev
            SENTRY_REDIS_HOST: redis
